version: 2.1

defaults: &defaults
  working_directory: ~/snapshift-mobile

jobs:
  build:
    <<: *defaults
    docker:
      - image: cimg/ruby:2.6.3
      - image: cimg/node:12.16

    steps:
      - checkout

      - run:
          name: install bundler
          command: gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - v3-snap-native-bundle-{{ checksum "Gemfile.lock" }}
            - v3-snap-native-bundle-

      - run:
          name: Bundle install
          command: bundle install --path=vendor/bundle

      - save_cache:
          key: v3-snap-native-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: ls -la
          command: ls -la

      - restore_cache:
          keys:
            - v1-snap-native-node-modules-{{ checksum "package-lock.json" }}

      - run:
          name: npm install
          command: npm install

      - save_cache:
          key: v1-snap-native-node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/snapshift-mobile
          paths:
            - node_modules


      - persist_to_workspace:
          root: ~/snapshift-mobile
          paths:
            - vendor/bundle

  ios-build:
    <<: *defaults
    macos:
      xcode: 12.5.1

    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: Fastlane
          command: bundle exec fastlane ios beta
          working_directory: ios


  android-build:
    <<: *defaults
    docker:
      - image: circleci/android:api-29-node

    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: ls -la
          command: ls -la

      - run:
          name: Fastlane
          command: bundle exec fastlane ios beta
          working_directory: ios

workflows:
  version: 2
  build-ios-android:
    jobs:
      - build
      - android-build:
          requires:
            - build
      - ios-build:
          requires:
            - build
