version: 2.1
jobs:
  build:
    working_directory: ~/snapshift-mobile
    docker:
      - image: cimg/node:12.16
      - image: circleci/ruby:2.6.3-stretch

    steps:
      - checkout

      # Set Ruby version
 #     - run:
 #         name: Set Ruby Version
 #         command:  echo "2.6.3" > .ruby-version

#      - run:
#          name: test
#          command:  ls -la


#      - run:
#          name: install bundler
#          command: gem install bundler



      - restore_cache:
          keys:
            - v3-snap-native-bundle-{{ checksum "Gemfile.lock" }}
            - v3-snap-native-bundle-

      - run:
          name: Bundle install
          command: bundle install --path=vendor/bundle

      - save_cache:
          key: v3-snap-native-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - v1-snap-native-node-modules{{ checksum "package-lock.json" }}

      - run:
          name: npm install
          command: npm install

      - save_cache:
          key: v1-snap-native-node-modules{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/snapshift-mobile
          paths:
            - node_modules
            - vendor/bundle

  ios-build:
    macos:
      xcode: 12.5.1

    steps:
      - attach_workspace: 
          at: ~/snapshift-mobile
      - run:
          name: Fastlane
          command: bundle exec fastlane ios beta
          working_directory: ios


  android-build:
    docker:
      - image: circleci/android:api-29-node

    steps:
      - attach_workspace:
          at: ~/snapshift-mobile
      - run:
          name: Fastlane
          command: bundle exec fastlane ios beta
          working_directory: ios

workflows:
  node-android-ios:
    jobs:
      - build
      - android-build:
          requires:
            - build
      - ios-build:
          requires:
            - build
